### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by pthane** [ds4ling/programming_assignments#19]
Hi @jvcasillas ,

I was wondering if you could remind me of the steps for the push request, specifically when comparing versions.  I know that we talked about this two weeks ago in class (selecting the correct repo and making it so that the arrow "lined up" with the correct repo), and I know that there was a trick that you taught us so that we could manipulate the branches such that I could push mine to the master (yours).  Would you be able to remind me of these steps?

Thanks,
PT

**Comment by jvcasillas** [comment]
The basic explanation is here: https://ds4ling.github.io/sources/tuts/github_setup/index.html#251_submitting_pull_requests

The thing you have to remember is that you need to send your changes to the master repo. This means for this to work correctly you need to select your repo from the pull down on the right and the ds4ling master repo from the pull down on the left. The way we did this in class was by selecting a random for from the pull down on the right first, then changing the left side to ds4ling/master, then changing the right side to your repo. 

That's totally annoying, I know. To recap...

1. on the right side select a random fork (not yours)
2. on the left side select ds4ling master
3. on the right side select your repo

... that should do it.
